pub const DETECTOR_INTERNAL_SAMPLE_RATE: usize = 16000;
pub const MFCCS_EXTRACTOR_FRAME_LENGTH_MS: usize = 30;
pub(crate) const COMPARATOR_DEFAULT_BAND_SIZE: u16 = 5;
pub(crate) const DETECTOR_DEFAULT_AVG_THRESHOLD: f32 = 0.2;
pub(crate) const DETECTOR_DEFAULT_THRESHOLD: f32 = 0.5;
pub(crate) const DETECTOR_DEFAULT_MIN_SCORES: usize = 5;
pub(crate) const DETECTOR_DEFAULT_REFERENCE: f32 = 0.22;
pub(crate) const MFCCS_EXTRACTOR_FRAME_SHIFT_MS: usize = 10;
pub(crate) const MFCCS_EXTRACTOR_PRE_EMPHASIS: f32 = 0.97;
pub(crate) const MFCCS_EXTRACTOR_OUT_SHIFTS: usize =
    MFCCS_EXTRACTOR_FRAME_LENGTH_MS / MFCCS_EXTRACTOR_FRAME_SHIFT_MS;
pub(crate) const NN_NONE_LABEL: &str = "none";
